name: Clojure CI to Heroku

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install shadow-cljs and deps
        run: npm install -g shadow-cljs & npm install react
      - name: Compile frontend
        run: shadow-cljs release app
      - uses: actions/upload-artifact@master
        with:
          name: main.js
          path: resources/public/js/main.js
        
  Build-backend:
    needs: [Build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: main.js
          path: resources/public/js/main.js
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: lein deps
      - name: Compile backend
        run: lein uberjar
      - uses: actions/upload-artifact@master
        with:
          name: foo.jar
          path: target/foo-0.0.1-SNAPSHOT-standalone.jar
        
  Deploy-to-heroku:
    needs: [Build-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: foo.jar
          path: foo.jar
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Heroku-cli and deps
        run: npm install -g heroku && heroku plugins:install java
      - run: pwd
      - run: ls -lah
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku deploy:jar ./foo.jar --app clojure-clock-fullstack-app
